### ISSUE TITLE
🐛 Bug ➾ taqueria does not properly forward error message from Michelson error message

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1858]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

`TAQ_LIGO_IMAGE=ligolang/ligo:next taq compile main.jsligo`

```
=== Error messages for main.jsligo ===
stderr maxBuffer length exceeded

===
┌─────────────┬──────────────┐
│ Contract    │ Artifact     │
├─────────────┼──────────────┤
│ main.jsligo │ Not compiled │
└─────────────┴──────────────┘
```

If I run with ligo 
```
ligo compile contract ./contracts/main.jsligo
```

logs :
```
{ "id": "proto.015-PtLimaPt.michelson_v1.entrypoint_name_too_long",
  "description":
    "An entrypoint name exceeds the maximum length of 31 characters.",
  "data":
    { "name": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAorgMemberRequestsUpdated" } }
```

### 🆘 Steps to Reproduce?

real issue is that the event name lenght is too long , ligo can show the actual error

Taqueria does not propagates the real error to the developer

### 🐘 How impactful is this bug?

None

### 💻 Operating System

None

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

0.28.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
@zamrokk do you have an example contract I can use to test with please?

**Comment by ManasJayanth** [comment]
I couldn't repro this myself. Even with older ligo docker images. But, looking at the report, it looks like the issue stems from `maxBuffer` of exec'd child processes. 

> === Error messages for main.jsligo ===
> stderr maxBuffer length exceeded

This could be because either, node.js was older and supported a smaller stderr buffer (recent ones support 1024 * 1024 chars) or if older lima protocol was throwing a long error message.

Ref: https://nodejs.org/api/child_process.html#maxbuffer-and-unicode

@mweichert Would you like me to open a PR raising the `maxBuffer` limit?

**Comment by zamrokk** [comment]
I cannot reproduce either on last ligoV1 version on nairobi

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/a2004264-c59e-45c6-98af-c3df205c6b14)

**Comment by zamrokk** [comment]
I close it so
